# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1paaz0MpWJMkiSLDzbkxrBGFfDTJ2Cwxg
"""

# Python program to reverse a string: 

LetsUpgrade="edargpUsteL" #string
print(LetsUpgrade[::-1]) #printing the string in reverse order